version: "3"
services:
#  mysql:
#    image: mysql
#    ports:
#      - "3306:3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_USER=peers
#      - MYSQL_PASSWORD=password
  consul:
    image: consul
    ports:
      - "8500:8500"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
  rabbitmq:
    image: holydocker13579/rabbitmq
    ports:
      - "61613:61613"
      - "15672:15672"
      - "5672:5672"

